#!/usr/bin/env bash

set -e

retrieve-patch() {
    local patch="$1"
    if [ -e "$patch" ]; then
        mv "$patch" "$patch.bak"
    fi
    git show patches:"$patch" > "${patch##*/}"
}

apply-patch() {
    local patch="$1"
    local components="${2:-1}"
    retrieve-patch "$patch"
    patch "-p$components" < "${patch##*/}"
}

retrieve-source() {
    cd "$root"
    local refspec="$1"
    local subdir="$2"
    mkdir -p "$subdir"
    git archive "$refspec" | tar -x -C "$subdir"
}

find-code-files() {
    find -name '*.C' -type f \
      -or -name '*.cc' -type f \
      -or -name '*.h' -type f
}

replace-fpu_control-with-fenv() {
    # fpu_control.h is not available on all systems. fenv.h is more common.
    find-code-files | while read -r file; do
        sed -i \
          -e 's/fpu_control.h/fenv.h/g' \
          -e 's/fpu_control_t oldcw, newcw;/fenv_t fenv;/g' \
          -e 's/_FPU_GETCW.*/fegetenv(\&fenv); fenv.__control_word \&= ~0x300; fenv.__control_word |= 0x200; fesetenv(\&fenv);/g' \
          -e 's/.*defined(_FPU_EXTENDED).*/#ifdef __linux__/' \
          "$file"
    done
}

fix-literal-suffix() {
    find-code-files | while read -r file; do
        sed -i -e 's/"\(PRI[iu]64\)/" \1/g' -e 's/\(PRI[iu]64\)"/\1 "/g' "$file"
    done
}

fix-uint64-format() {
    find-code-files | while read -r file; do
        sed -i \
          -e 's/%ll[du]/%" PRIu64 "/g' \
          -e 's/\(nbSimplifyAll         : \)%d/\1%" PRIu64 "/' \
          -e 's/%i\(\\n",\(duplicates\|conflicts\|duptime\)\)/%" PRIu64 "\1/' \
          "$file"
    done
}

fix-Clause_new() {
    find-code-files | while read -r file; do
        sed -i \
          -e 's/friend Clause/static Clause/' \
          -e 's/= Clause_new/= Clause::Clause_new/' \
          -e 's/(Clause_new/(Clause::Clause_new/' \
          "$file"
    done
}

fix-drup-segfault() {
    find-code-files | while read -r file; do
        sed -i -e 's/saved_size!=c.size()/drup_file \&\& \0/' "$file"
    done
}

strip-symbols() {
    for file in "$@"; do
        objcopy -S "$file"
    done
}

fetch() {
    local subdir="$1"
    local refspec="${2:-$1}"
    echo
    printf "%s\n" $'\e'"[1mbuilding $subdir..."$'\e'"[0m"
    retrieve-source "$refspec" "$builds/$subdir"
    cd "$builds/$subdir"
}

fetch-and-prepare() {
    fetch "$1" "$2"
    apply-patch OpenBSD/patch-minisat_core_SolverTypes_h 1
    fix-literal-suffix
    replace-fpu_control-with-fenv
}

build-and-install() {
    local name="$1"
    cd simp
    make rs
    cp *_static "$bin/$name"
}

build-common() {
    local solver="$1"
    fetch-and-prepare "$solver"
    build-and-install "$solver"
}

build-minisat-2.0() {
    fetch minisat-2.0 minisat2-070721

    apply-patch minisat-2.0-silence-warnings.patch 2
    fix-Clause_new
    replace-fpu_control-with-fenv

    cd simp
    # for some reason, flags get ignored if not set explicitly.
    make rs CFLAGS="$MINISAT_2_0_CFLAGS $CFLAGS"
    cp minisat_static "$bin/minisat-2.0"
}

build-minisat-2.2.0() {
    fetch-and-prepare minisat-2.2.0
    build-and-install minisat-2.2.0
}

build-minisat-master() {
    fetch minisat-master master

    apply-patch OpenBSD/patch-minisat_core_SolverTypes_h 0
    apply-patch OpenBSD/patch-minisat_core_Solver_cc 0
    apply-patch OpenBSD/patch-minisat_utils_Options_h 0
    apply-patch OpenBSD/patch-minisat_utils_System_cc 0
    replace-fpu_control-with-fenv

    make r
    cp build/release/bin/minisat "$bin/minisat-master"
}

build-glucose-1.0() {
    fetch glucose-1.0

    apply-patch glucose-1.0-silence-warnings.patch 2
    fix-Clause_new
    replace-fpu_control-with-fenv

    cd sources/glucose/core
    # flags need to be set explicitly, else a 32-bit binary is *always* built.
    make rs CFLAGS="$MINISAT_2_0_CFLAGS $CFLAGS" LFLAGS="--static -lz"
    cp glucose_static "$bin/glucose-1.0"
}

build-glucose-2.0() {
    fetch glucose-2.0

    cd sources/glucose
    apply-patch OpenBSD/patch-minisat_core_SolverTypes_h 1
    fix-literal-suffix
    fix-uint64-format
    replace-fpu_control-with-fenv

    # there's a simp directory, but it's not used for this version.
    cd core
    make rs
    cp glucose_static "$bin/glucose-2.0"
}

build-glucose-2.1() {
    fetch glucose-2.1

    cd sources/glucose
    apply-patch OpenBSD/patch-minisat_core_SolverTypes_h 1
    fix-literal-suffix
    fix-uint64-format
    replace-fpu_control-with-fenv

    # there's a simp directory, but it's not used for this version.
    cd core
    make rs
    cp glucose_static "$bin/glucose-2.1"
}

build-glucose-3.0() {
    fetch-and-prepare glucose-3.0
    fix-uint64-format
    build-and-install glucose-3.0
}

build-glucose-4.0() {
    fetch glucose-4.0
    replace-fpu_control-with-fenv
    build-and-install glucose-4.0
}

build-glucose-4.1() {
    fetch glucose-4.1
    replace-fpu_control-with-fenv
    build-and-install glucose-4.1
}

build-minisat-to-glucose() {
    fetch-and-prepare minisat-to-glucose minisat-2.2.0
    apply-patch COMiniSatPS/minisat-2.2.0-to-glucose.patch
    apply-patch COMiniSatPS/binary-watches.patch
    build-and-install minisat-to-glucose
}

build-COMiniSatPS-01() {
    fetch-and-prepare COMiniSatPS-01 minisat-2.2.0
    apply-patch COMiniSatPS/01_minisat2glucoseSC13.patch
    build-and-install COMiniSatPS-01
}

build-COMiniSatPS-02() {
    fetch-and-prepare COMiniSatPS-02 minisat-2.2.0
    apply-patch COMiniSatPS/01_minisat2glucoseSC13.patch
    apply-patch COMiniSatPS/02_SWDiA5BY_SC14.patch
    build-and-install COMiniSatPS-02
}

build-COMiniSatPS-2015() {
    fetch-and-prepare COMiniSatPS-2015 15fabea
    build-and-install COMiniSatPS-2015
}

build-COMiniSatPS-2016() {
    fetch-and-prepare COMiniSatPS-2016 e2642bb
    build-and-install COMiniSatPS-2016
}

build-MapleCOMSPS() {
    fetch-and-prepare MapleCOMSPS
    build-and-install MapleCOMSPS
}

build-MapleLCM() {
    fetch-and-prepare MapleLCM
    fix-uint64-format
    fix-drup-segfault
    build-and-install MapleLCM
}

build-MapleLCMDist() {
    fetch MapleLCMDist
    replace-fpu_control-with-fenv
    fix-literal-suffix
    fix-drup-segfault
    build-and-install MapleLCMDist
}

build-MapleCM() {
    fetch MapleCM
    replace-fpu_control-with-fenv
    fix-literal-suffix
    fix-uint64-format
    build-and-install MapleCM
}

build-MapleLCMDistChronoBT() {
    fetch MapleLCMDistChronoBT
    replace-fpu_control-with-fenv
    fix-literal-suffix
    build-and-install MapleLCMDistChronoBT
}

build-MapleLCMDistChronoBTDLv3() {
    fetch MapleLCMDistChronoBTDLv3
    replace-fpu_control-with-fenv
    fix-literal-suffix
    fix-uint64-format
    build-and-install MapleLCMDistChronoBTDLv3
}

root="$(readlink -f "$(dirname "$0")" )"
bin="$root/bin"
builds="$root/builds"

flags=(
    -Wno-misleading-indentation
    -Wno-unused-but-set-variable
    -Werror=literal-suffix
)

if [[ "$CC" =~ clang* ]] || [[ "$CXX" =~ clang* ]]; then
    flags+=(
        -Wno-unknown-warning-option
        -Wno-ignored-optimization-argument
        -Wno-logical-op-parentheses
        -Wno-dangling-else
        -Wno-bitwise-op-parentheses
    )
fi

mkdir -p "$bin"
mkdir -p "$builds"

MINISAT_2_0_CFLAGS="-I../mtl -I../core -Wall -ffloat-store -O3 -D NDEBUG"

export MROOT=../
export CXXFLAGS="${flags[@]}"
export CFLAGS="${flags[@]}"

build-minisat-2.0
build-minisat-2.2.0
build-minisat-master
build-glucose-1.0
build-glucose-2.0
#build-glucose-2.1 # currently broken
build-glucose-3.0
build-glucose-4.0
build-glucose-4.1
build-minisat-to-glucose
build-COMiniSatPS-01
build-COMiniSatPS-02
build-COMiniSatPS-2015
build-COMiniSatPS-2016
build-MapleCOMSPS
build-MapleLCM
build-MapleLCMDist
build-MapleCM
build-MapleLCMDistChronoBT
build-MapleLCMDistChronoBTDLv3

cd "$root"

strip-symbols "$bin"/*
